### ISSUE TITLE
How to implement the swagger following this structure?

### ISSUE THREAD

**Issue by riquedev** [santiq/bulletproof-nodejs#102]
I am using the same structure as the repository for an internal project and I felt the need to document the routes, I would like to try to integrate this scope into Swagger, is there any example of this?

**Comment by lineldcosta** [comment]
I have implemented the similar in this repo https://github.com/lineldcosta/typescript-node-rest-api-boilerplate

**Comment by riquedev** [comment]
> I have implemented the similar in this repo https://github.com/lineldcosta/typescript-node-rest-api-boilerplate

Thanks!!
