### ISSUE TITLE
Absolute import "Cannot find module @/*"

### ISSUE THREAD

**Issue by nayyaung9** [santiq/bulletproof-nodejs#115]
I have cloned and installed necessary dependencies.
When I run yarn start, I got

```
[nodemon] starting `ts-node  --transpile-only ./src/app.ts`
Error: Cannot find module '@/config'
Require stack:
- /home/react/Desktop/friends-backend/src/loaders/logger.ts
- /home/react/Desktop/friends-backend/src/app.ts
```

I am not sure why this is happening. I restart or clean cache my vs code and yarn package. But it does not still work.

**Comment by Nikola-Milovic** [comment]
@nayyaung9  how did your resolve this? I am using the "@/config" as import path but still getting errors

@RobertoGallego  is any extra setup needed besides installing tsconfig-paths? I tried installing it and I get the same error. 

```
// loaders/logger.ts
import config from "@/config";
```

**Comment by nayyaung9** [comment]
@Nikola-Milovic  Using absolute import in local is work well. But when deploying on heroku. it show "module not found" :((
But I used with relative paths in heroku. @RobertoGallego  Is there any extra config for that?

**Comment by Nikola-Milovic** [comment]
@nayyaung9  can you reopen the issue? It seems we could use some help on this :rofl:

**Comment by RobertoGallego** [comment]
Hello, i didnt try to run with Heroku, I gave u 2 options for the issue, that works for me, i made some changes for the  tsconfig-paths, in the package.json i modified my api like this: ``` "api": "nodemon --exec ts-node -r tsconfig-paths/register src/index.ts", ```
then change the app.js for index.js

cheers hope u can fix
