### ISSUE TITLE
Problem in winston instance with typescript

### ISSUE THREAD

**Issue by diomalta** [santiq/bulletproof-nodejs#13]
**Problem**

When the logger is instance by decorators it works fine with this.logger.error() the ts recognizes the methods.
![image](https://user-images.githubusercontent.com/22456325/59646137-f0339d80-914b-11e9-8ea4-6609157cae5c.png)

But calling through a container typescript does not understand that there are methods(error, info and debug).
![image](https://user-images.githubusercontent.com/22456325/59646259-7f40b580-914c-11e9-8ec8-dc2bbb1e4a8a.png)

This is error what typescript return
![image](https://user-images.githubusercontent.com/22456325/59646274-9f707480-914c-11e9-84bc-feaf53b95052.png)

**Comment by santiq** [comment]
Hello @diomalta 
Try adding a type to the variable like this: 

```javascript
const logger: any = Container.get('logger')
```
