### ISSUE TITLE
Events and jobs

### ISSUE THREAD

**Issue by mintyPT** [santiq/bulletproof-nodejs#15]
Hey,

Thank you for this repo. 2 questions for you:

Where do you use the events? 
Where do you put the line between a job and an event?

**Comment by santiq** [comment]
Hi @mintyPT 

The events are used when you need to perm a task in 'background' **after** a certain action occurs.

For example, a user signups in your application, that should fire an event, where the subscribers/listeners are things like sending the welcome email or create a company for that user.
Another example is an analytics system that you can implement in the backend.
Every time a user creates an item for his todo list you track that _serverside_ saving metadata in the database.

And the difference between a job and event is that the event is just `'A new user was created'` or `user.created`  -> `src/subsribers/user.ts`

And the job is the actual code that gets executed when that event is fired -> `src/jobs/emailSequence.ts`

**Comment by mintyPT** [comment]
Thank you for your answer.

But still, where do you use events? I don't see the code about triggering the event.

**Comment by santiq** [comment]
Oh I see 😅 

I never trigger the event, I'd had missed it.

The idea is to trigger it here on Line 53, just after sending the signup email.

https://github.com/santiq/bulletproof-nodejs/blob/master/src/services/auth.ts#L53


```js
this.logger.silly('Sending welcome email');
await this.mailer.SendWelcomeEmail(userRecord);
this.eventDispatcher.dispatch(events.user.signUp, { user: userRecord })
```


I'll update the code shortly, thanks for letting me know!!

**Comment by Jfelix61** [comment]
I'll be implementing this shortly.
