### ISSUE TITLE
Add agenda typescript implementation

### ISSUE THREAD

**Issue by Jfelix61** [santiq/bulletproof-nodejs#16]
Before the question, Thanks for the boilerplate it has been a breeze to use. 

Is there any plan to implement agenda with typescript since it has a DefinetlyTyped type definitions available?

**Comment by santiq** [comment]
Hi @Jfelix61 
I'm glad you liked this boilerplate.

Sure, we can add the TS definitions for agenda and the corresponding types in the codebase it should be pretty easy.

**Comment by Jfelix61** [comment]
I can add it.

**Comment by santiq** [comment]
@Jfelix61 that would be great!

**Comment by santiq** [comment]
Solved #19
