### ISSUE TITLE
Issue with agenda jobs

### ISSUE THREAD

**Issue by zlydenko** [santiq/bulletproof-nodejs#34]
Hi, can you clear some things about agenda jobs? You're awaiting not async function

https://github.com/santiq/bulletproof-nodejs/blob/9c1cd2af3ccd812fd36085d1f9aa8f8f9351bd4b/src/jobs/emailSequence.ts#L11

https://github.com/santiq/bulletproof-nodejs/blob/9c1cd2af3ccd812fd36085d1f9aa8f8f9351bd4b/src/services/mailer.ts#L10

**Comment by santiq** [comment]
Of course! Thanks for notice it :)
