### ISSUE TITLE
nodemon not saved in devDependencies

### ISSUE THREAD

**Issue by rwoody** [santiq/bulletproof-nodejs#47]
nodemon is not saved to devDependencies in package.json and the project will not start after a clone, `npm install` and `npm start`.

**Comment by santiq** [comment]
Thanks! Feel free to open a PR to fix this :)

**Comment by felipediogo** [comment]
#49 - done, nice project btw.

**Comment by santiq** [comment]
Solved in #49 
Thanks @felipediogo !!
