### ISSUE TITLE
Question: Is this a good practice to put some data in req object ?

### ISSUE THREAD

**Issue by LucasLelaidier** [santiq/bulletproof-nodejs#50]
Hello, im learning nodejs thanks to your tutorial and i was wondering if it is a good practice to pass data through req object as you did here ?

https://github.com/santiq/bulletproof-nodejs/blob/3e64b149708db269f09d1daff71a3e339aa73b9d/src/api/middlewares/attachCurrentUser.ts#L22

Wouldn't be better to give it as parameter in the next middleware ?

Sorry if its off topic 😅 (and thanks for this repo)

**Comment by blankstar85** [comment]
It is kinda getting passed as a parameter. the express middleware takes request, response, next as parameters. So the current user is getting attached to the request, making it available to any of the following middlewares that get used down the line. ( no matter how many there may be).

**Comment by LucasLelaidier** [comment]
Indeed it seems ok to add data to req object like this. I thought that it was weird to add data to an object like this but JS is different... 😄
