### ISSUE TITLE
Error: Cannot find module 'argon2' (npm)

### ISSUE THREAD

**Issue by Chris8800** [santiq/bulletproof-nodejs#53]
Hello santiq and team, 

I am trying to install the bulletproofNJS. I am stuck in powershell with trying to install argon2 via npm. I am getting the error msg after the failed install: 

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\[user]\Documents\bulletproof\bulletproof-nodejs-master\node_modules\argon2\build\libargon2.vcxproj]

I have already installed python27 and also configured the env variables. I need some help with the Windows SDK. 

Kind Regards and thx

**Comment by Chris8800** [comment]
npm install --process windows-build-tools does the trick and configuring the right path for env variables for python2.

**Comment by cnscorpions** [comment]
already with python 3.6 installed. What a mess to work with python 2. :(
