### ISSUE TITLE
Testing routes auth.ts and user.ts with postman executes the error not found

### ISSUE THREAD

**Issue by Chris8800** [santiq/bulletproof-nodejs#54]
When testing the routes from the user.ts and the auth.ts files in routes, the express.ts error method is giving me an error msg. It seems that the routes auth.ts and user.ts is not responding to express.ts. How can this be fixed or what am I doing wrong?

**Comment by santiq** [comment]
Hello @Chris8800 can you post a screenshot or paste the response from postman? 
That should include both the request you are performing and the response returned by the server.

**Comment by Chris8800** [comment]
Hello @santiq and thanks for the fast reply! I have changed the path to http://localhost:3000/api/auth/signup and I am getting the error message: {
    "errors": {
        "message": "child \"name\" fails because [\"name\" is required]"
    }
}. This is the same message as explained in the docs of your git. I am not sure how to interpret it.

**Comment by santiq** [comment]
It says that the property `name` is required on the request body, try adding that.

**Comment by Chris8800** [comment]
I have put my JSON into a raw format on postman.
 ```
{
	"name": "Joe Fring",
	"email": "joe.minus@mail.com",
	"password": "123456LL"
}
```

**Comment by Chris8800** [comment]
![snip20 01 2020](https://user-images.githubusercontent.com/38652551/72728224-270fdd00-3b8d-11ea-8602-c6feceed393c.PNG)

**Comment by Chris8800** [comment]
My mistake! Wrong config in postman.
