### ISSUE TITLE
await userRecord.save(); can not save data to mongodb

### ISSUE THREAD

**Issue by cnscorpions** [santiq/bulletproof-nodejs#71]
Hi, i found that call save() not work when I'd like to save data to database.

code as follows:
```
 const userRecord = await this.userModel.create({
                ...userDTO,
                salt,
                password: hashedPwd,
            });

            // save to database
            await userRecord.save();
```

endpoint api works well, and return 
```
{
    "user": {
        "role": "user",
        "_id": "5ed08b923de44903c4ad5320",
        "name": "admin",
        "email": "404398jiwerewtwr34235kjgelg",
        "createdAt": "2020-05-29T04:12:02.662Z",
        "updatedAt": "2020-05-29T04:12:02.662Z",
        "__v": 0
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWQwOGI5MjNkZTQ0OTAzYzRhZDUzMjAiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJhZG1pbiIsImV4cCI6MTU5MDcyNTUyMi42NzYsImlhdCI6MTU5MDcyNTUyMn0.oy4IP3sZ6sga12-yjXZN9sr03fx4V3c-KFWF_Jq_OWM"
}
```

but in my mongodb docker container,
I search users by `users.find({})`,
error comes out as follows:
```
2020-05-29T04:07:49.242+0000 E  QUERY    [js] uncaught exception: ReferenceError: users is not defined :
```

Any help will be appreciated.
BTW, this architecture is good, but seems not suitable for small project. :(
It takes several hours for me to figure out how it works.

Thanks

**Comment by varunagarwal315** [comment]
I think the CLI command would be `db.users.find()` for mongoDB. Can you explain how you are searching for the users from the container?

**Comment by cnscorpions** [comment]
sorry for my mistake. The right query should be `db.users.find({})`; 😂 so closed this issue.

**Comment by cnscorpions** [comment]
sorry for my mistake. The right query should be db.users.find({}); 😂 so closed this issue.
