### ISSUE TITLE
Socket.io implementation

### ISSUE THREAD

**Issue by midnightblurz** [santiq/bulletproof-nodejs#73]
Hello! I was wondering what would be the correct way to implement socket.io in this project, any ideas?

**Comment by santiq** [comment]
Hello @midnightblurz 

Just add a new loader like in `loaders/socket-io.js` where you attach the socket.io instance to the express app.

Then register the socket.io instance into the Dependency Injection container, similar to how the instance of the Event Emitter is registered. 

Finally, to use it, inject it on the classes you want to emit socket events, like the event emitter.

Socket.io and the Event Emitter are pretty similar.

I hope this helps!

**Comment by midnightblurz** [comment]
Got it! Thanks for the help

**Comment by arghyac35** [comment]
> Hello @midnightblurz
> 
> Just add a new loader like in `loaders/socket-io.js` where you attach the socket.io instance to the express app.
> 
> Then register the socket.io instance into the Dependency Injection container, similar to how the instance of the Event Emitter is registered.
> 
> Finally, to use it, inject it on the classes you want to emit socket events, like the event emitter.
> 
> Socket.io and the Event Emitter are pretty similar.
> 
> I hope this helps!

Can u please show an example code of how to implement the same?

**Comment by jeffreyvdhondel** [comment]
> > Hello @midnightblurz
> > Just add a new loader like in `loaders/socket-io.js` where you attach the socket.io instance to the express app.
> > Then register the socket.io instance into the Dependency Injection container, similar to how the instance of the Event Emitter is registered.
> > Finally, to use it, inject it on the classes you want to emit socket events, like the event emitter.
> > Socket.io and the Event Emitter are pretty similar.
> > I hope this helps!
> 
> Can u please show an example code of how to implement the same?

Yeah that would be great. I can't figure it out.

**Comment by 13bscsaamjad** [comment]
If it is still relevant, you could do something like

`src/app.ts`
```javascript
const app = express();
const httpServer = createServer(app);
await require('./loaders').default({ expressApp: app, httpServer: httpServer });
```

`src/loaders/index.ts`
```javascript
await SocketServer({ httpServer });
```

And have a loader as pointed by @santiq which loads class implementing the SocketServer `src/loaders/socket-io.ts`
```javascript
export default ({ httpServer }) => {
  new SocketServer(httpServer);
};
```

And implement the socket server class like `src/socketio/socketio.ts`
```javascript
import { Server } from 'socket-io';

export default class SocketServer {
  constructor(httpServer) {
    this.io = new Server(httpServer);
    this.listen();
  }

  private listen() {
    const Logger: Logger = Container.get('logger');
    Logger.silly(`SocketServer listening!`);

    this.io.on('connection', (socket: Socket) => {
      Logger.silly(`Client connected to SocketServer: ${socket.id}`);
      
      socket.on('disconnect', () => {
            Logger.silly(`Client disconneted from SocketServer: ${socket.id}`);
      });
    });
  }
}
```

And have decorators for different events like `EventDispatcher` to be injected into service classes.

Hope it helps 😊
