### ISSUE TITLE
type of "User Model" for the injected user model in constructor??

### ISSUE THREAD

**Issue by riodel27** [santiq/bulletproof-nodejs#82]
![image (4)](https://user-images.githubusercontent.com/25262915/92225100-56cde400-eed5-11ea-9966-c09c76b782b2.png)

**Comment by SamsadSajid** [comment]
How did you solved it?

**Comment by riodel27** [comment]
> How did you solve it?

![image](https://user-images.githubusercontent.com/25262915/95807007-b83a6b80-0d3b-11eb-91a2-edd322681967.png)

**Comment by SamsadSajid** [comment]
You could also solve it by adding paths in your `tsconfig`.

```
"baseUrl": ".",
    "paths": {
      "*": ["src/types/*"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "src"
    ],
```
