### ISSUE TITLE
Updating to Node v14

### ISSUE THREAD

**Issue by ent3r** [santiq/bulletproof-nodejs#84]
Node v14 is going into LTS in just over a month (see [https://nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/)). Would it be smart to update this repo to work with Node v14?

**Comment by midnightblurz** [comment]
I've updated the project to support v14

Pull request: [https://github.com/santiq/bulletproof-nodejs/pull/85](https://github.com/santiq/bulletproof-nodejs/pull/85)
Fork: [https://github.com/midnightblurz/bulletproof-nodejs/tree/node_v14_migration](https://github.com/midnightblurz/bulletproof-nodejs/tree/node_v14_migration)

**Comment by santiq** [comment]
Thanks guys, I'll check this out over the weekend.

**Comment by ent3r** [comment]
I haven't looked that much at the code yet, but I'm pretty sure some stuff could be improved by using new functions from v11, v12, v13, and v14. One such thing is [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by midnightblurz** [comment]
Thought you needed it to run on v14, because i couldn't run the project without errors on newer node versions. Didn't think about modifying the code too much, but i will give it a try!

**Comment by ent3r** [comment]
Yeah, i was originally thinking about just getting it to run on v14, but i later realised that using some of the utilities from v11-14 would be useful
